networks:
  default:
    driver: bridge

services:
  wf-express:
    image: wf-express:latest
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: ./.env-dev
    command: ["yarn", "dev"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"